language: ruby

cache: bundler

services:
  - postgresql

node_js:
  - '0.6'

addons:
  postgresql: '9.4'
  firefox: latest-beta

before_script:
  - npm install bower
  - bundle exec rake bower:install
  - psql -c 'create database mykonote_test;' -U postgres
