language: ruby

cache: bundler

services:
  - postgresql

addons:
  postgresql: '9.4'

before_script:
  - npm install bower
  - bundle exec rake bower:install
  - psql -c 'create database mykonote_test;' -U postgres
