language: ruby

cache: bundler

services:
  - postgresql

addons:
  postgresql: '9.4'
  firefox: latest-beta

before_script:
  - bundle exec rake client:npm_install
  - bundle exec rake client:build_and_deploy
  - psql -c 'create database mykonote_test;' -U postgres
