default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  <% if ENV['POSTGRESQL_USER'].present? %>
  username: <%= ENV['POSTGRESQL_USER'] %>
  <% end %>
  <% if ENV['POSTGRESQL_PASSWORD'].present? %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  <% end %>
  <% if ENV['POSTGRESQL_HOST'].present? %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  <% end %>
  <% if ENV['POSTGRESQL_PORT'].present? %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
  <% end %>

development:
  <<: *default
  database: mykonote_development

test:
  <<: *default
  database: mykonote_test

production:
  <<: *default
  database: rails_production
  username: app
